name: shop_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.7.0' # Энэ хэвээрээ байна

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  dynamic_color: ^1.6.8
  json_annotation: ^4.8.1
  provider: ^6.1.1

  # ✅ Firebase (web compatible & compatible versions)
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_auth_web: ^5.14.3
  cloud_firestore: ^5.6.0
  js: ^0.7.2
  firebase_messaging: ^15.2.6 # ЭНЭ ХУВИЛБАРЫГ ӨӨРЧИЛНӨ ҮҮ!
  # firebase_messaging_web: # Энэ мөр хасагдсан хэвээрээ байна.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true


# android:
#   minSdkVersion: 23

  assets:
    - assets/products.json
    - assets/users.json