// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS9sf90DIDgyB_X8wiUuh7eyyjUiiApT8',
    appId: '1:258871947207:web:16afb5adca716845c5f3e2',
    messagingSenderId: '258871947207',
    projectId: 'mobile-shalgalt',
    authDomain: 'mobile-shalgalt.firebaseapp.com',
    storageBucket: 'mobile-shalgalt.firebasestorage.app',
    measurementId: 'G-BEG0191N1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5YPgqHQ6n_15bNGTwHf2D9OygN036Eyw',
    appId: '1:258871947207:android:f7bc3a10d7c65541c5f3e2',
    messagingSenderId: '258871947207',
    projectId: 'mobile-shalgalt',
    storageBucket: 'mobile-shalgalt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEhck3D9Z-nX1u_WDEoSvW8_E6YjNKKa4',
    appId: '1:258871947207:ios:89830bd03d6f8621c5f3e2',
    messagingSenderId: '258871947207',
    projectId: 'mobile-shalgalt',
    storageBucket: 'mobile-shalgalt.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEhck3D9Z-nX1u_WDEoSvW8_E6YjNKKa4',
    appId: '1:258871947207:ios:89830bd03d6f8621c5f3e2',
    messagingSenderId: '258871947207',
    projectId: 'mobile-shalgalt',
    storageBucket: 'mobile-shalgalt.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS9sf90DIDgyB_X8wiUuh7eyyjUiiApT8',
    appId: '1:258871947207:web:bfed8c944cdd3e38c5f3e2',
    messagingSenderId: '258871947207',
    projectId: 'mobile-shalgalt',
    authDomain: 'mobile-shalgalt.firebaseapp.com',
    storageBucket: 'mobile-shalgalt.firebasestorage.app',
    measurementId: 'G-JY4TP4P622',
  );
}
